language: python
python: 
  - "2.7"

install:
  - echo "Aqui se instalan las dependencias"
#  - pip install django

before_script:
  - echo "Antes de ejecutar un script"

script:
  - echo "Pruebas unitarias de Calculadora"
  - python Test*.py
  - echo "finalizar"
notifications:
email: false